Домашнее задание 1

In [2]:
from unittest.mock import right

import numpy as np

In [12]:
#Задача 1: Создайте одномерный массив из 5 целых чисел от 0 до 4
l = list(range(5))
print(l)

[0, 1, 2, 3, 4]


In [20]:
#Задача 2: Создайте массив размером 3x2, заполненный единицами.
np.ones((3, 2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [3]:
#Задача 3: Создайте массив размером 2x3, заполненного значением 7.
np.full((2, 3), '7')

array([['7', '7', '7'],
       ['7', '7', '7']], dtype='<U1')

In [4]:
#Задача 4: Создайте массив из 5 строк и 2 столбцов, содержащий только булевы значения True
np.full((2, 3), True)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [25]:
#Задача 5: Как создать массив из 5 равномерно распределенных значений между 0 и 1 с использованием np.linspace()?
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Домашнее задание 2

In [11]:
#Задача 1: Создайте трехмерный массив (каждый массив должен содержать две строки и четыре столбца) и определите его количество измерений.
array = np.random.randint(10, size=(3, 2, 4))
print(array)
print(f'Количество измерений: {array.ndim}')

[[[2 2 8 1]
  [5 9 0 2]]

 [[8 9 0 8]
  [8 0 5 9]]

 [[9 1 9 4]
  [1 0 6 9]]]
Количество измерений: 3


In [19]:
#Задача 2: Вы хотите создать массив arr с числами от 1 до 3, включительно, и указать явно тип данных целых чисел.
arr = np.array([1, 2, 3], dtype=int)
print(f'Массив целых чисел: {arr}')
print(f'Тип данных: {arr.dtype}')

Массив целых чисел: [1 2 3]
Тип данных: int64


In [22]:
#Задача 3: Выведите все элементы в нечетных столбцах
arr = np.array([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12],
        [13, 14, 15, 16]])

print(arr[::,0::2])

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [31]:
#Задача 4: Выделите подматрицу, состоящую из второй и третьей строк, а также третьего и четвёртого столбцов
matrix = np.array([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12],
            [13, 14, 15, 16]])

print(matrix[1:3,2:4])

[[ 7  8]
 [11 12]]


In [34]:
#Задача 5: Выберите подматрицу 2x2 в верхнем левом углу для каждой матрицы
tensor = np.array([[[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]],
            [[10, 11, 12],
            [13, 14, 15],
            [16, 17, 18]],
            [[19, 20, 21],
            [22, 23, 24],
            [25, 26, 27]]])

print(tensor[:, :2, :2])

[[[ 1  2]
  [ 4  5]]

 [[10 11]
  [13 14]]

 [[19 20]
  [22 23]]]
